server:
  port: 8080
spring:
  application:
    name: users
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mariadb://localhost:11111/concertly
    username: ${CONCERTLY_DATABASE_USERNAME}
    password: ${CONCERTLY_DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver